export const dashboardConfig = {
  stats: [
    {
      id: "total-balance",
      title: "Total Balance",
      value: "$124,500",
      change: "+12%",
      changeType: "positive",
      icon: "account_balance",
      color: "blue",
    },
    {
      id: "monthly-income",
      title: "Monthly Income",
      value: "$8,200",
      change: "+5%",
      changeType: "positive",
      icon: "payments",
      color: "emerald",
    },
    {
      id: "monthly-outflow",
      title: "Monthly Outflow",
      value: "$3,500",
      change: "-2%",
      changeType: "negative",
      icon: "shopping_cart",
      color: "orange",
    },
    {
      id: "net-savings",
      title: "Net Savings",
      value: "$4,700",
      change: "+8%",
      changeType: "positive",
      icon: "savings",
      color: "purple",
    },
  ],
  incomeExpenseChart: {
    title: "Income vs Expenses",
    subtitle: "Last 6 Months",
    data: [
      { month: "May", income: 60, expense: 40 },
      { month: "Jun", income: 75, expense: 45 },
      { month: "Jul", income: 65, expense: 30 },
      { month: "Aug", income: 85, expense: 50 },
      { month: "Sep", income: 90, expense: 55 },
      { month: "Oct", income: 80, expense: 35 },
    ],
  },
  portfolio: {
    title: "Portfolio",
    total: "$45,000",
    change: "+15.4%",
    changeType: "positive",
    allocations: [
      {
        name: "Stocks",
        value: "$27,000",
        percentage: 60,
        color: "primary",
      },
      {
        name: "Mutual Funds",
        value: "$11,250",
        percentage: 25,
        color: "purple-500",
      },
      {
        name: "Crypto",
        value: "$4,500",
        percentage: 10,
        color: "orange-500",
      },
      {
        name: "Cash",
        value: "$2,250",
        percentage: 5,
        color: "emerald-500",
      },
    ],
  },
  upcomingEmis: [
    {
      id: 1,
      title: "Home Loan",
      bank: "HDFC Bank",
      amount: "$1,200",
      dueDate: "Oct 25",
      status: "due-soon",
    },
    {
      id: 2,
      title: "Car Loan",
      bank: "Toyota Finance",
      amount: "$450",
      dueDate: "Nov 02",
      status: "upcoming",
    },
  ],
  savingsGoals: [
    {
      id: 1,
      title: "Trip to Japan",
      icon: "flight",
      current: 3200,
      target: 5000,
      color: "emerald",
    },
    {
      id: 2,
      title: "Emergency Fund",
      icon: "shield",
      current: 8500,
      target: 10000,
      color: "blue",
    },
    {
      id: 3,
      title: "New MacBook",
      icon: "laptop_mac",
      current: 600,
      target: 2500,
      color: "purple",
    },
  ],
  recurringPayments: {
    title: "Recurring",
    total: "$128/mo",
    items: [
      {
        id: 1,
        name: "Netflix",
        icon: "movie",
        frequency: "Monthly",
        nextDate: "Oct 28",
        amount: "-$15.99",
        color: "red",
      },
      {
        id: 2,
        name: "Spotify",
        icon: "music_note",
        frequency: "Family Plan",
        nextDate: "Nov 01",
        amount: "-$12.99",
        color: "green",
      },
      {
        id: 3,
        name: "Internet",
        icon: "wifi",
        frequency: "AT&T Fiber",
        nextDate: "Nov 05",
        amount: "-$89.00",
        color: "blue",
      },
    ],
  },
};
