export const portfolioStats = [
  {
    id: 1,
    title: "Current Value",
    value: "$45,231.00",
    icon: "trending_up",
    iconBgColor: "bg-green-500/10",
    iconColor: "text-[#0bda5b]",
    trend: {
      value: "+10.2%",
      label: "vs last month",
      color: "text-[#0bda5b]",
    },
  },
  {
    id: 2,
    title: "Invested Amount",
    value: "$41,110.50",
    icon: "account_balance_wallet",
    iconBgColor: "bg-blue-500/10",
    iconColor: "text-primary",
    subLabel: "Across 12 Funds",
  },
  {
    id: 3,
    title: "Total Returns",
    value: "+$4,120.50",
    icon: "monetization_on",
    iconBgColor: "bg-green-500/10",
    iconColor: "text-[#0bda5b]",
    trend: {
      value: "+10.02%",
      label: "overall return",
      color: "text-[#0bda5b]",
    },
  },
];

export const assetAllocation = [
  {
    id: 1,
    category: "Equity",
    percentage: 60,
    color: "bg-primary",
    dotColor: "bg-primary",
  },
  {
    id: 2,
    category: "Debt",
    percentage: 25,
    color: "bg-[#0bda5b]",
    dotColor: "bg-[#0bda5b]",
  },
  {
    id: 3,
    category: "Gold/Others",
    percentage: 15,
    color: "bg-amber-400",
    dotColor: "bg-amber-400",
  },
];

export const holdings = [
  {
    id: 1,
    fundName: "Vanguard S&P 500 ETF",
    shortName: "V",
    category: "Equity",
    categoryColor: "blue",
    avatarBg: "bg-blue-100 dark:bg-blue-900/30",
    avatarColor: "text-primary",
    invested: 5000.0,
    currentValue: 5450.0,
    returns: 450.0,
    returnsPercentage: 9.0,
    isPositive: true,
  },
  {
    id: 2,
    fundName: "Invesco QQQ Trust",
    shortName: "Q",
    category: "Equity",
    categoryColor: "blue",
    avatarBg: "bg-purple-100 dark:bg-purple-900/30",
    avatarColor: "text-purple-600 dark:text-purple-400",
    invested: 8500.0,
    currentValue: 9780.0,
    returns: 1280.0,
    returnsPercentage: 15.1,
    isPositive: true,
  },
  {
    id: 3,
    fundName: "Gold ETF Fund",
    shortName: "G",
    category: "Commodity",
    categoryColor: "amber",
    avatarBg: "bg-amber-100 dark:bg-amber-900/30",
    avatarColor: "text-amber-600 dark:text-amber-400",
    invested: 3200.0,
    currentValue: 3310.0,
    returns: 110.0,
    returnsPercentage: 3.4,
    isPositive: true,
  },
  {
    id: 4,
    fundName: "Bond Market Index",
    shortName: "B",
    category: "Debt",
    categoryColor: "green",
    avatarBg: "bg-green-100 dark:bg-green-900/30",
    avatarColor: "text-green-600 dark:text-green-400",
    invested: 10000.0,
    currentValue: 9950.0,
    returns: -50.0,
    returnsPercentage: -0.5,
    isPositive: false,
  },
  {
    id: 5,
    fundName: "Fidelity Blue Chip",
    shortName: "F",
    category: "Equity",
    categoryColor: "blue",
    avatarBg: "bg-blue-100 dark:bg-blue-900/30",
    avatarColor: "text-primary",
    invested: 4000.0,
    currentValue: 4230.0,
    returns: 230.0,
    returnsPercentage: 5.7,
    isPositive: true,
  },
];

export const chartTimeframes = [
  { id: "1m", label: "1M", active: false },
  { id: "6m", label: "6M", active: false },
  { id: "1y", label: "1Y", active: true },
  { id: "all", label: "ALL", active: false },
];
