export const recurringStats = [
  {
    id: 1,
    title: "Total Monthly Outflow",
    value: "$2,450.00",
    icon: "payments",
    iconColor: "text-[#9dabb9]",
    trend: {
      value: "2.4% less than last month",
      type: "down",
      color: "text-emerald-400",
    },
  },
  {
    id: 2,
    title: "Upcoming in 7 Days",
    value: "$135.98",
    icon: "calendar_clock",
    iconColor: "text-[#9dabb9]",
    subLabel: "3 payments due soon",
  },
  {
    id: 3,
    title: "Overdue Amount",
    value: "$45.00",
    icon: "warning",
    iconColor: "text-red-400",
    subLabel: "Action required immediately",
    subLabelColor: "text-red-400",
    isAlert: true,
  },
];

export const recurringPayments = [
  {
    id: 1,
    serviceName: "Spotify Premium",
    description: "Family Plan",
    category: "Subscription",
    frequency: "Monthly",
    amount: 16.99,
    nextDue: "Sep 28, 2023",
    dueInfo: "In 2 days",
    status: "pending",
    statusText: "Pending",
    icon: "music_note",
    iconBg: "bg-[#1ed760]/10",
    iconColor: "text-[#1ed760]",
  },
  {
    id: 2,
    serviceName: "Home Loan EMI",
    description: "Chase Bank",
    category: "Loan",
    frequency: "Monthly",
    amount: 1200.0,
    nextDue: "Oct 01, 2023",
    dueInfo: "Auto-pay on",
    status: "scheduled",
    statusText: "Scheduled",
    icon: "home",
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-500",
  },
  {
    id: 3,
    serviceName: "Gold's Gym",
    description: "Membership",
    category: "Health",
    frequency: "Monthly",
    amount: 45.0,
    nextDue: "Sep 15, 2023",
    dueInfo: "11 days overdue",
    dueInfoColor: "text-red-400",
    status: "overdue",
    statusText: "Overdue",
    icon: "fitness_center",
    iconBg: "bg-red-500/10",
    iconColor: "text-red-500",
  },
  {
    id: 4,
    serviceName: "AT&T Fiber",
    description: "Internet Bill",
    category: "Utility",
    frequency: "Monthly",
    amount: 60.0,
    nextDue: "Sep 25, 2023",
    dueInfo: "Paid yesterday",
    dueInfoColor: "text-emerald-500",
    status: "paid",
    statusText: "Paid",
    icon: "wifi",
    iconBg: "bg-purple-500/10",
    iconColor: "text-purple-500",
  },
  {
    id: 5,
    serviceName: "Netflix",
    description: "Standard Plan",
    category: "Subscription",
    frequency: "Monthly",
    amount: 15.99,
    nextDue: "Sep 29, 2023",
    dueInfo: "In 3 days",
    status: "pending",
    statusText: "Pending",
    icon: "movie",
    iconBg: "bg-red-600/10",
    iconColor: "text-red-600",
  },
];

export const statusColors = {
  pending: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
  scheduled: "bg-blue-500/10 text-blue-500 border-blue-500/20",
  overdue: "bg-red-500/10 text-red-500 border-red-500/20",
  paid: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
};

export const filterOptions = {
  categories: ["All", "Subscription", "Loan", "Utility", "Health"],
  statuses: ["All", "Pending", "Scheduled", "Overdue", "Paid"],
  sortBy: ["Date", "Amount", "Name"],
};
