export const transactionStats = [
  {
    id: 1,
    title: "Total Income",
    value: "$4,250.00",
    icon: "trending_up",
    iconBg: "bg-green-500/10",
    iconColor: "text-green-500",
    trend: {
      value: "+12%",
      label: "vs last month",
      color: "text-green-500",
    },
  },
  {
    id: 2,
    title: "Total Expenses",
    value: "$2,100.50",
    icon: "trending_down",
    iconBg: "bg-red-500/10",
    iconColor: "text-red-500",
    trend: {
      value: "+5%",
      label: "vs last month",
      color: "text-red-500",
    },
  },
  {
    id: 3,
    title: "Net Balance",
    value: "$2,149.50",
    icon: "account_balance_wallet",
    iconBg: "bg-primary/10",
    iconColor: "text-primary",
    trend: {
      value: "+8%",
      label: "saving rate",
      color: "text-primary",
    },
  },
];

export const transactions = [
  {
    id: 1,
    date: "Oct 24, 2023",
    title: "Netflix Subscription",
    description: "Monthly Plan",
    category: "Entertainment",
    type: "Recurring",
    status: "completed",
    statusText: "Completed",
    amount: -15.99,
    icon: "movie",
    iconBg: "bg-red-100 dark:bg-red-500/20",
    iconColor: "text-red-600 dark:text-red-400",
  },
  {
    id: 2,
    date: "Oct 22, 2023",
    title: "HDFC Mutual Fund",
    description: "SIP Investment",
    category: "Investment",
    type: "SIP",
    status: "completed",
    statusText: "Completed",
    amount: -500.0,
    icon: "trending_up",
    iconBg: "bg-blue-100 dark:bg-blue-500/20",
    iconColor: "text-blue-600 dark:text-blue-400",
  },
  {
    id: 3,
    date: "Oct 20, 2023",
    title: "Salary Credit",
    description: "Tech Solutions Inc.",
    category: "Income",
    type: "Salary",
    status: "completed",
    statusText: "Completed",
    amount: 3500.0,
    icon: "payments",
    iconBg: "bg-green-100 dark:bg-green-500/20",
    iconColor: "text-green-600 dark:text-green-400",
  },
  {
    id: 4,
    date: "Oct 18, 2023",
    title: "Starbucks",
    description: "Coffee & Snacks",
    category: "Food & Drink",
    type: "One-time",
    status: "completed",
    statusText: "Completed",
    amount: -8.5,
    icon: "restaurant",
    iconBg: "bg-orange-100 dark:bg-orange-500/20",
    iconColor: "text-orange-600 dark:text-orange-400",
  },
  {
    id: 5,
    date: "Oct 15, 2023",
    title: "Bali Trip Fund",
    description: "Internal Transfer",
    category: "Savings",
    type: "Transfer",
    status: "pending",
    statusText: "Pending",
    amount: -200.0,
    icon: "flight",
    iconBg: "bg-purple-100 dark:bg-purple-500/20",
    iconColor: "text-purple-600 dark:text-purple-400",
  },
];

export const statusColors = {
  completed:
    "bg-green-100 dark:bg-green-500/20 text-green-700 dark:text-green-400 border-green-200 dark:border-green-500/30",
  pending:
    "bg-yellow-100 dark:bg-yellow-500/20 text-yellow-700 dark:text-yellow-400 border-yellow-200 dark:border-yellow-500/30",
  failed:
    "bg-red-100 dark:bg-red-500/20 text-red-700 dark:text-red-400 border-red-200 dark:border-red-500/30",
};

export const filterOptions = {
  categories: [
    "All Categories",
    "Income",
    "Entertainment",
    "Investment",
    "Food & Drink",
    "Savings",
    "Shopping",
    "Transport",
  ],
  types: ["All Types", "Recurring", "One-time", "SIP", "Salary", "Transfer"],
  dateRanges: [
    "Last 7 Days",
    "Last 30 Days",
    "This Month",
    "Last Month",
    "Custom Range",
  ],
};
